public with sharing class ResponseWrapper {

//	public String folder_id;
//	public String status;
//	public String case_id;
//	List<ResponseFileEntityTest> errors;
//
//	public ResponseEntityTest(String folderId, String caseId) {
//		this.folder_id = folderId;
//		this.case_id = caseId;
//		this.errors = new List<ResponseFileEntityTest>();
//	}
//
//	public void prepareResponse() {
//		this.setStatus();
//	}
//
//	private void setStatus() {
//
//		if(case_id == null) {
//			status = 'failure';
//		} else if(errors.isEmpty()) {
//			status = 'success';
//		} else {
//			status = 'partial success';
//		}
//	}
//
//	public class ResponseFileEntityTest {
//
//		public String entity_id;
//		public String message;
//
//		public ResponseFileEntityTest(String entityId, String errorMessage) {
//			this.entity_id = entityId;
//			this.message = errorMessage;
//		}
//	}
}